06_DB/20240409_NtoM/practice/db_ws_6_a/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<username>/', views.profile, name='profile'),
]

06_DB/20240409_NtoM/practice/db_ws_6_a/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('mypage/', views.my_page, name='my_page'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('<int:todo_pk>/delete/', views.delete, name='delete'),
    path('<int:todo_pk>/update/', views.update, name='update'),
    path('<int:todo_pk>/recommend/', views.recommend, name='recommend'),
]

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    recommend_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='recommend_todos')
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = '__all__'
        exclude = ('user', 'recommend_users' )
        widgets = {'is_completed': forms.HiddenInput()}

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Todo
from .forms import TodoForm

# Create your views here.
def index(request):
    todo_list = Todo.objects.all()
    context = {
        'todo_list': todo_list
    }
    return render(request, 'todos/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()
            return redirect('todos:detail', todo.pk)
    else:
        form = TodoForm()
    context = {
        'form': form
    }
    return render(request, 'todos/create.html', context)
    
def detail(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/detail.html', context)

@login_required
def delete(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    if request.user == todo.user:
        if request.method == 'POST':
            todo.delete()
            return redirect('todos:index')
    return redirect('todos:detail', todo.pk)

@login_required
def update(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    if request.user == todo.user:
        if request.method == 'POST':
            form = TodoForm(request.POST, instance=todo)
            if form.is_valid():
                todo = form.save()
        else:
            form = TodoForm(instance=todo)
        context = {
            'todo': todo,
            'form': form
        }
        return render(request, 'todos/update.html', context)
    return redirect('todos:detail', todo.pk)

def my_page(request):
    todo_list = request.user.todo_set.all()
    context = {
        'todo_list': todo_list
    }
    return render(request, 'todos/my_page.html', context)

def recommend(request, todo_pk):
    if request.method == 'POST':
        todo = Todo.objects.get(pk=todo_pk)
        if request.user in todo.recommend_users.all():
            todo.recommend_users.remove(request.user)
        else:
            todo.recommend_users.add(request.user)
    return redirect('todos:index')

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/templates/todos/create.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>

  <form action="{% url "todos:create" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
{% endblock content %}

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/templates/todos/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 상세 페이지</h1>
  <hr>
  <p>{{ todo.pk }}번 째 할 일</p>
  <p>작 성 : {{ todo.user.username }}</p>
  <p>할 일 : {{ todo.work }}</p>
  <p>내 용 : {{ todo.content }}</p>
  <p>일 자 : {{ todo.created_at }}</p>
  <p>완 료 : {{ todo.is_completed }}</p>
  <hr>
  {% if request.user == todo.user %}
    <a href="{% url "todos:my_page" %}">[내 할 일 목록으로 돌아가기]</a>
    <a href="{% url "todos:update" todo.pk %}">수정</a>
    <form action="{% url "todos:delete" todo.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제">
    </form>
  {% endif %}
{% endblock content %}

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/templates/todos/index.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 관리 프로젝트 메인 페이지</h1>
  <p>이 곳에서 할 일 목록을 관리합니다.</p>
  <ul>
    {% for todo in todo_list %}
    <li>
        {% if request.user != todo.user %}
          <form action="{% url "todos:recommend" todo.pk %}" method="POST">
            {% csrf_token %}
            {% if request.user in  todo.recommend_users.all %}
              <input type="submit" value="★">
            {% else %}
              <input type="submit" value="☆">
            {% endif %}
          </form>
        {% endif %}
        <p>작 성 : <a href="{% url "accounts:profile" todo.user.username %}">{{ todo.user.username }}</a></p>
        <input type="checkbox" value="{{ todo.is_completed }}" {% if todo.is_completed %}checked{% endif %}>
        <a href="{% url "todos:detail" todo.pk %}">{{ todo.work }}</a>
      </li>
    {% empty %}
      <li>아직 할 일이 없습니다.</li>
    {% endfor %}
  </ul>
{% endblock content %}

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/templates/todos/my_page.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ user.username }}님의 할 일 목록 페이지</h1>
  <ul>
    {% for todo in todo_list %}
      <li>
        <p>작 성 : {{ todo.user.username }}</p>
        <input type="checkbox" value="{{ todo.is_completed }}" {% if todo.is_completed %}checked{% endif %}>
        <a href="{% url "todos:detail" todo.pk %}">{{ todo.work }}</a>
      </li>
    {% empty %}
      <li>아직 할 일이 없습니다.</li>
    {% endfor %}
  </ul>
{% endblock content %}

06_DB/20240409_NtoM/practice/db_ws_6_a/todos/templates/todos/update.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
{% endblock content %}