06_DB/20240404_Nto1/practice/db_ws_4_3/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

06_DB/20240404_Nto1/practice/db_ws_4_3/convenience_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stores/', include('stores.urls')),
    path('accounts/', include('accounts.urls')),
]

06_DB/20240404_Nto1/practice/db_ws_4_3/stores/urls.py
from django.urls import path
from . import views


app_name = 'stores'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:store_pk>/', views.detail, name='detail'),
    path('<int:store_pk>/create_product', views.create_product, name='create_product'),
    path('create/', views.create_store, name='create_store'),
]

06_DB/20240404_Nto1/practice/db_ws_4_3/stores/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Store(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    is_franchise = models.BooleanField()

class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    amount = models.IntegerField()
    price = models.IntegerField()
    adult = models.BooleanField()

06_DB/20240404_Nto1/practice/db_ws_4_3/stores/forms.py
from django import forms
from .models import Product, Store

class StoreForm(forms.ModelForm):

    class Meta:
        model = Store
        fields = '__all__'


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'amount', 'price', 'adult',)

06_DB/20240404_Nto1/practice/db_ws_4_3/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm

User = get_user_model()
# Create your views here.
def index(request):
    members = User.objects.all()
    context = {
        'members': members
    }
    return render(request, 'accounts/index.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('stores:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    if request.method == 'POST':
        auth_logout(request)
    return redirect('accounts:login')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('stores:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

06_DB/20240404_Nto1/practice/db_ws_4_3/stores/views.py
from django.shortcuts import render, redirect
from .models import Store, Product
from .forms import StoreForm, ProductForm

# Create your views here.
def index(request):
    stores = Store.objects.all()
    context = {
        'stores': stores
    }
    return render(request, 'stores/index.html', context)

def detail(request, store_pk):
    store = Store.objects.get(pk=store_pk)
    form = ProductForm()
    context = {
        'store': store,
        'form' : form,
    }
    return render(request, 'stores/detail.html', context)

def create_store(request):
    if request.method == 'POST':
        form = StoreForm(request.POST)
        if form.is_valid():
            store = form.save()
            return redirect('stores:detail', store.pk)
    else:
        form = StoreForm()
    context = {
        'form' : form,
    }
    return render(request, 'stores/create.html', context)

def create_product(request, store_pk):
    store = Store.objects.get(pk=store_pk)
    form = ProductForm(request.POST)
    if form.is_valid():
        product = form.save(commit=False)
        product.user = request.user
        product.store = store
        product.save()
        return redirect('stores:detail', store_pk)
    return redirect('stores:detail', store_pk)

06_DB/20240404_Nto1/practice/db_ws_4_3/stores/templates/stores/create.html
{% extends "base.html" %}

{% block content %}
<h1>신규 매장 등록 페이지</h1>

<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="등록">
</form>
<a href="{% url "stores:index" %}">[돌아가기]</a>
{% endblock content %}

06_DB/20240404_Nto1/practice/db_ws_4_3/stores/templates/stores/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>편의점 상세 정보</h1>
  <p>점장 : {{ store.user }}</p>
  <p>주소 : {{ store.address }}</p>
  <p>체인점 여부 : {{ store.is_franchise }}</p>
  <hr>
  <h3>신규 상품 등록</h3>
  <form action="{% url "stores:create_product" store.pk%}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="물품 등록">
  </form>
  <hr>
  <h3>전체 상품 목록</h3>
  <ul>
    {% for product in store.product_set.all %}
      <li>이름 : {{product.name}}</li>
      <li>가격 : {{product.price}}</li>
      <br>
    {% endfor %}
  </ul>
  <a href="{% url 'stores:index' %}">[전체 목록 보기]</a>
{% endblock content %}

06_DB/20240404_Nto1/practice/db_ws_4_3/stores/templates/stores/index.html
{% extends 'base.html' %}

{% block content %}
<h1>전체 편의점 목록</h1>

<a href="{% url "stores:create_store" %}">[신규 매장 등록]</a>
<ul>
  {% for store in stores %}
  <a href="{% url 'stores:detail' store.pk %}">
    <li>점장 : {{ store.user.username }}</li>
    <li>주소 : {{ store.address }}</li>
  </a>
  <hr>
  {% endfor %}
</ul>
{% endblock content %}